let sd="1004",cd="1004";const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const iu=f=>{if(f&&typeof f==='object')return f.u;return /^https?:/.test(f)?f:'https://commons.wikimedia.org/wiki/Special:FilePath/'+encodeURIComponent(f)+'?width=1600'},sp=f=>{if(f&&typeof f==='object')return f.s||f.u;return /^https?:/.test(f)?f:'https://commons.wikimedia.org/wiki/File:'+encodeURIComponent(f)};
const ACTIONS={
"1002":{level:"watch",kind:"预约",dateLabel:"WATCH",item:"北齐壁画博物馆",title:"北齐壁画博物馆预约",note:"国庆预约与讲解规则临行复核；五人会合后的第一站，提前确认最稳。"},
"1003":{level:"urgent",kind:"预约",date:"2026-09-18",dateLabel:"09.18",item:"云冈石窟",title:"云冈石窟预约窗口",note:"按当前提前15日的规则，10/3门票预计9/18起可预约。国庆专项规则发布后再次复核。"},
"1004":{level:"critical",kind:"抢票",dateLabel:"DATE TBD",item:"悬空寺登临票",title:"悬空寺登临票",note:"全程最高抢票风险。国庆放票时间与批次一旦公布，优先处理登临票。"},
"1007":{level:"watch",kind:"预约",date:"2026-10-04",dateLabel:"10.04?",item:"山西博物院",title:"山西博物院预约",note:"按常规提前3日规则估算为10/4左右；国庆预约周期与开放安排仍需专项复核。"}
};
function cnDayIndex(){let n=new Date(Date.now()+8*3600000);return Math.floor(Date.UTC(n.getUTCFullYear(),n.getUTCMonth(),n.getUTCDate())/86400000)}
function actionStatus(a){if(!a.date)return a.dateLabel;let p=a.date.split('-').map(Number),t=Math.floor(Date.UTC(p[0],p[1]-1,p[2])/86400000),d=t-cnDayIndex();if(d>1)return`D-${d}`;if(d===1)return'明日';if(d===0)return'今日';return'已开放'}
function actionCard(a,day,compact=false){return `<div class="action-card action-${a.level}${compact?' compact':''}"><div class="action-top"><span>${a.level==='critical'?'ACTION REQUIRED':a.level==='urgent'?'NEXT ACTION':'RESERVE'}</span><em>${a.kind}</em></div><div class="action-main"><div class="action-date">${actionStatus(a)}</div><div><div class="action-title">${a.title}</div><div class="action-note">${a.note}</div></div></div>${day?`<button class="action-open" data-action-day="${day}">打开当天 →</button>`:''}</div>`}
function openActionDay(id){sd=id;rj();od(id)}
function bindActionLinks(root=document){root.querySelectorAll('.action-open').forEach(b=>b.onclick=()=>openActionDay(b.dataset.actionDay))}
function renderHomeActions(){let host=$('#homeActions');if(!host){host=document.createElement('div');host.id='homeActions';host.className='home-actions';$('#enter').parentElement.insertAdjacentElement('beforebegin',host)}host.innerHTML=`<div class="action-desk-head"><span>Action Desk / 行动提醒</span><b>先处理会影响成行的事</b></div>${actionCard(ACTIONS['1003'],'1003',true)}${actionCard(ACTIONS['1004'],'1004',true)}`;bindActionLinks(host)}
function renderTicketQueue(){return `<div class="ticket-desk"><div class="ticket-desk-title">ACTION QUEUE</div><div class="ticket-desk-sub">按抢票风险与时间顺序处理；国庆专项规则发布后继续更新。</div>${['1003','1004','1002','1007'].map(id=>actionCard(ACTIONS[id],id)).join('')}</div>`}
function show(v){$$('section').forEach(x=>x.classList.remove('on'));$('#'+v).classList.add('on');$$('nav button').forEach(b=>b.classList.toggle('on',b.dataset.v===v||(v==='day'||v==='place')&&b.dataset.v==='journey'));scrollTo(0,0);if(v==='map')setTimeout(initMap,60)}$$('nav button').forEach(b=>b.onclick=()=>show(b.dataset.v));$('#enter').onclick=()=>show('journey');
function rj(){let h='';D.forEach(d=>{let a=ACTIONS[d[0]],alert=a?`<span class="journey-alert alert-${a.level}">${a.kind} · ${actionStatus(a)}</span>`:'';h+=`<div class="jrow ${d[0]===sd?'sel':''}"><button data-id="${d[0]}" aria-label="打开 ${d[1]} ${d[3]}"><div><div class="jdate">${d[1]}</div><div class="tiny" style="margin-top:7px">${d[2]}</div></div><div><div class="jtitle">${d[3]}</div><div class="sub">${d[4]}</div>${alert}</div><div class="en wood" style="font-size:9px">${d[5]} ↗</div></button></div>`});$('#jlist').innerHTML=h;$$('.jrow button').forEach(b=>b.onclick=()=>{sd=b.dataset.id;rj();od(sd)});let d=D.find(x=>x[0]===sd);$('#sumt').textContent=d[1]+' · '+d[3];$('#sumn').textContent=d[7]}$('#opend').onclick=()=>od(sd);renderHomeActions();