let sd="1004",cd="1004";const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const iu=f=>{if(f&&typeof f==='object')return f.u;return /^https?:/.test(f)?f:'https://commons.wikimedia.org/wiki/Special:FilePath/'+encodeURIComponent(f)+'?width=1600'},sp=f=>{if(f&&typeof f==='object')return f.s||f.u;return /^https?:/.test(f)?f:'https://commons.wikimedia.org/wiki/File:'+encodeURIComponent(f)};
const ACTIONS={
"1002":{level:"urgent",kind:"预约",date:"2026-09-22",dateLabel:"09.22",item:"北齐壁画博物馆",title:"北齐壁画博物馆国庆预约",note:"9/16最新公告：国庆严格实名分时预约，可提前10天预约，约满关闭且原则上不开放临时登记。10/2名额从9/22起关注；与山西博物院AM/PM可互换。"},
"1003":{level:"urgent",kind:"预约",date:"2026-09-18",dateLabel:"09.18",item:"云冈石窟",title:"云冈石窟预约窗口",note:"按2026年现行提前15日（不含当日）规则，10/3门票预计9/18起可预约；国庆专项规则发布后再次复核。"},
"1004":{level:"critical",kind:"抢票",date:"2026-09-27",dateLabel:"09.27 20:00",item:"悬空寺登临票",title:"悬空寺登临票",note:"10/4登临票按现行规则有两次线上放票机会：9/27 20:00与9/28 07:20。线上总量有限，第一时间处理。",moments:[{at:"2026-09-27T20:00:00+08:00",label:"20:00"},{at:"2026-09-28T07:20:00+08:00",label:"07:20"}]}
};
const BOOKINGS={
"1002":{channel:"微信公众号",name:"太原北齐壁画博物馆",official:"https://kandian.sina.cn/article_5812119316_15a6de71402001ia3i.html?from=news",route:"微信搜索并关注“太原北齐壁画博物馆” → 预约购票 / 门票预约 → 选择10月2日与时段 → 填写实名信息。",tip:"2026年9月16日最新规则：春节、五一、中秋、国庆实行实名分时预约，可提前10天预约；每日、每时段限量，约满即关闭，原则上不开放临时登记。多数优待人群也需预约；国庆期间一卡通不可使用。"},
"1003":{channel:"微信小程序",name:"云冈石窟文旅",alt:"云冈研究院",official:"https://www.dt.gov.cn/dt12345/rxdt1/202604/29b73c0aa08148e3baca536eb7166bb9.shtml",route:"微信搜索“云冈石窟文旅”或“云冈研究院” → 门票预约 → 选择10月3日与时段 → 实名购票。",tip:"2026年4月15日起预约周期调整为提前15日（不含当日）。"},
"1004":{channel:"微信小程序",name:"北岳云游",official:"https://www.byhs.net.cn/Travel_Guide/1.html",latest:"https://www.thepaper.cn/newsDetail_forward_33421772",route:"景点购票 → 景区门票 → 悬空寺景点 → 悬空寺登临门票 → 去预定 → 选择日期/场次 → 添加购票人 → 立即购买。",tip:"登临需同时具备入园票与登临票。普通H5无法可靠直跳微信小程序，页面提供一键复制小程序名和官方票务/放票规则入口。",windows:[{d:"09.27",t:"20:00–23:00",label:"第一批 · 600张"},{d:"09.28",t:"07:20–18:00",label:"第二批 · 600张"}],prep:["提前在“北岳云游”完善购票人信息；开抢前几分钟进入登临票页面并停留等待。","同一手机为多人下单时，同行人员需要依次完成人脸识别，全部通过后才能排队下单。","若五人均购成人票，按景区当前票务页每单成人票数量限制与单账号下单规则，至少提前准备多个账号/手机；异地抢票时每人各自下单最省刷脸时间。","小红书用户实操建议：20:00前进入购买页，看到“请20点后进行购票”时先留在页面，等到放票时点再提交，减少重新进入页面的耗时。","此前官方检票规则明确：上午票可在下午时段继续检票，下午票不能提前到上午使用；2026国庆前再复核是否有专项调整。"]}
};
const PLACE_ACTION={beiqi:"1002",yungang:"1003",hanging:"1004"};
function cnDayIndex(){let n=new Date(Date.now()+8*3600000);return Math.floor(Date.UTC(n.getUTCFullYear(),n.getUTCMonth(),n.getUTCDate())/86400000)}
function actionStatus(a){if(a.moments&&a.moments.length){let now=Date.now(),m=a.moments.find(x=>Date.parse(x.at)>now);if(!m)return'已开抢';let day=m.at.slice(0,10).split('-').map(Number),t=Math.floor(Date.UTC(day[0],day[1]-1,day[2])/86400000),d=t-cnDayIndex();if(d>1)return`D-${d}`;if(d===1)return`明日 ${m.label}`;return`今日 ${m.label}`}if(!a.date)return a.dateLabel;let p=a.date.split('-').map(Number),t=Math.floor(Date.UTC(p[0],p[1]-1,p[2])/86400000),d=t-cnDayIndex();if(d>1)return`D-${d}`;if(d===1)return'明日';if(d===0)return'今日';return'已开放'}
function bookingEntry(day,compact=false){let b=BOOKINGS[day];if(!b)return'';let windows=b.windows&&!compact?`<div class="booking-windows">${b.windows.map(w=>`<div><b>${w.d}</b><strong>${w.t}</strong><span>${w.label}</span></div>`).join('')}</div>`:'';return `<div class="booking-entry${compact?' booking-compact':''}"><div class="booking-channel">${b.channel}</div><div class="booking-name">${b.name}${b.alt?` <span>/ ${b.alt}</span>`:''}</div>${windows}<div class="booking-route">${compact?'微信内搜索后进入官方预约入口。':b.route}</div><div class="booking-actions"><button class="copy-booking" data-booking="${b.name}">复制${b.channel==='微信小程序'?'小程序':'公众号'}名</button>${b.latest?`<a href="${b.latest}" target="_blank" rel="noopener">最新放票规则 ↗</a>`:''}<a href="${b.official}" target="_blank" rel="noopener">${b.latest?'景区票务页':'官方规则'} ↗</a></div>${!compact&&b.tip?`<div class="booking-tip">${b.tip}</div>`:''}</div>`}
function actionCard(a,day,compact=false){let b=BOOKINGS[day],windows=a.moments&&!compact&&b?.windows?`<div class="action-window-line">${b.windows.map(w=>`<span><b>${w.d}</b> ${w.t}</span>`).join('')}</div>`:'';return `<div class="action-card action-${a.level}${compact?' compact':''}"><div class="action-top"><span>${a.level==='critical'?'ACTION REQUIRED':a.level==='urgent'?'NEXT ACTION':'RESERVE'}</span><em>${a.kind}</em></div><div class="action-main"><div class="action-date">${actionStatus(a)}</div><div><div class="action-title">${a.title}</div><div class="action-note">${a.note}</div></div></div>${windows}${b?bookingEntry(day,compact):''}${day?`<button class="action-open" data-action-day="${day}">打开当天 →</button>`:''}</div>`}
function copyBookingName(name,btn){navigator.clipboard?.writeText(name).then(()=>{let old=btn.textContent;btn.textContent='已复制 ✓';setTimeout(()=>btn.textContent=old,1500)}).catch(()=>window.prompt('复制后到微信搜索：',name))}
function bindBookingLinks(root=document){root.querySelectorAll('.copy-booking').forEach(b=>b.onclick=()=>copyBookingName(b.dataset.booking,b))}
function openActionDay(id){sd=id;rj();od(id)}
function bindActionLinks(root=document){root.querySelectorAll('.action-open').forEach(b=>b.onclick=()=>openActionDay(b.dataset.actionDay));bindBookingLinks(root)}
function placeBookingPanel(placeId){let day=PLACE_ACTION[placeId],b=BOOKINGS[day];if(!b)return'';let prep=b.prep?`<div class="booking-prep">${b.prep.map((x,i)=>`<div><b>${String(i+1).padStart(2,'0')}</b><span>${x}</span></div>`).join('')}</div>`:'';return `<div class="place-booking"><div class="place-booking-head"><span>Booking / 预约入口</span><strong>${ACTIONS[day].kind}</strong></div>${bookingEntry(day,false)}${prep}</div>`}
function renderHomeActions(){let host=$('#homeActions');if(!host){host=document.createElement('div');host.id='homeActions';host.className='home-actions';$('#enter').parentElement.insertAdjacentElement('beforebegin',host)}host.innerHTML=`<div class="action-desk-head"><span>Action Desk / 行动提醒</span><b>先处理会影响成行的事</b></div>${actionCard(ACTIONS['1003'],'1003',true)}${actionCard(ACTIONS['1004'],'1004',true)}`;bindActionLinks(host)}
function renderTicketQueue(){return `<div class="ticket-desk"><div class="ticket-desk-title">ACTION QUEUE</div><div class="ticket-desk-sub">按抢票风险与时间顺序处理；国庆专项规则发布后继续更新。</div>${['1004','1003','1002'].map(id=>actionCard(ACTIONS[id],id)).join('')}</div>`}
function show(v){$$('section').forEach(x=>x.classList.remove('on'));$('#'+v).classList.add('on');$$('nav button').forEach(b=>b.classList.toggle('on',b.dataset.v===v||(v==='day'||v==='place')&&b.dataset.v==='journey'));scrollTo(0,0);if(v==='map')setTimeout(initMap,60)}$$('nav button').forEach(b=>b.onclick=()=>show(b.dataset.v));$('#enter').onclick=()=>show('journey');
function rj(){let h='';D.forEach(d=>{let a=ACTIONS[d[0]],alert=a?`<span class="journey-alert alert-${a.level}">${a.kind} · ${actionStatus(a)}</span>`:'';h+=`<div class="jrow ${d[0]===sd?'sel':''}"><button data-id="${d[0]}" aria-label="打开 ${d[1]} ${d[3]}"><div><div class="jdate">${d[1]}</div><div class="tiny" style="margin-top:7px">${d[2]}</div></div><div><div class="jtitle">${d[3]}</div><div class="sub">${d[4]}</div>${alert}</div><div class="en wood" style="font-size:9px">${d[5]} ↗</div></button></div>`});$('#jlist').innerHTML=h;$$('.jrow button').forEach(b=>b.onclick=()=>{sd=b.dataset.id;rj();od(sd)});let d=D.find(x=>x[0]===sd);$('#sumt').textContent=d[1]+' · '+d[3];$('#sumn').textContent=d[7]}$('#opend').onclick=()=>od(sd);renderHomeActions();