const PLACE_TICKETS={
shuanglin:{channel:"线上购票 H5",name:"平遥古城线上购票",kind:"预约购票",route:"打开“直接购票” → 选择双林寺 → 选择日期与时段 → 添加实名游客信息 → 完成购票。",tip:"已确认2026年7月起千佛殿实施保护修缮并半封闭，工期预计至2028年9月；目前未检索到9月新发布的国庆专项预约规则，继续以线上可售场次为准。",source:"https://youbaner.pingyao888.cn/#/",sourceLabel:"直接购票"},
zhenguo:{channel:"线上购票 H5",name:"平遥古城线上购票",kind:"预约购票",route:"打开“直接购票” → 选择镇国寺 → 选择日期与时段 → 添加实名游客信息 → 完成购票。",tip:"已确认2026年7月起万佛殿实施保护修缮并半封闭，工期预计至2027年9月；目前未检索到9月新发布的国庆专项预约规则，继续以线上可售场次为准。",source:"https://youbaner.pingyao888.cn/#/",sourceLabel:"直接购票"},
pingyao:{channel:"线上购票 H5",name:"平遥古城线上购票",kind:"预约购票",route:"打开“直接购票” → 选择平遥古城通票 → 选择日期 → 添加实名游客信息 → 完成购票。",tip:"进入古城街区本身免费；城墙、日昇昌、县衙等收费景点使用古城通票。目前未检索到9月新发布的国庆专项预约规则。",source:"https://youbaner.pingyao888.cn/#/",sourceLabel:"直接购票"},
tianlongshan:{channel:"微信公众号",name:"晋祠天龙山景区官微",alt:"太原市天龙山石窟博物馆",kind:"预约购票",route:"进入公众号 → 票务/线上购票 → 选择天龙山石窟博物馆 → 填写实名信息并支付。",tip:"景区实行线上线下一体化售票；截至9月17日未检索到新的国庆专项预约公告。现行旺季开放至10月31日，国庆客流较高仍建议提前线上处理。",source:"https://www.tylyhy.cn/wenlvzixun/2084543085798207490.html",sourceLabel:"近期官方开放信息"},
shanxi_museum:{channel:"微信公众号",name:"山西博物院",kind:"实名预约",route:"微信关注“山西博物院”公众号 / 订阅号 → 参观服务 → 实名预约 → 选择10月2日场次。",tip:"现行预约仍为提前3日（不含当天），每单最多3人，10/2按常规约9/29开放。另自2026年9月1日起停止使用入馆二维码：预约成功后须本人持身份证、护照等有效证件原件按预约时段入馆；60岁以上老人、军人等规定优待人群可凭有效证件免预约。",source:"https://shanximuseum.com.cn/sx/index/index.html",sourceLabel:"官方预约说明"},
huayan:{channel:"微信小程序",name:"古都大同",alt:"大同华严寺景区公众号",kind:"预约购票",route:"微信搜索“古都大同” → 购票 → 大同华严寺景区 → 选择日期与票种 → 实名支付。",tip:"2026旺季（4/1–10/31）全价票50元；截至9月17日未检索到国庆专项开放/预约新公告。节假日开放时间可能另行延长，出发前继续复核。",source:"https://www.dt.gov.cn/dt12345/tpxw4/202604/db21ff8389a7498ca80c869a9e0f6e43.shtml",sourceLabel:"2026旺季信息"},
shanhua:{channel:"微信小程序",name:"古都大同",alt:"大同善化寺公众号",kind:"预约购票",route:"微信搜索“古都大同” → 购票 → 善化寺 → 选择参观日期与时段 → 实名支付。",tip:"2026旺季继续执行全价40元；截至9月17日未检索到国庆专项开放/预约新公告。节假日开放时间可能另行延长，出发前继续复核。",source:"https://www.dt.gov.cn/dtszf/bumdtku/202507/dd38df65c6c84322a2355a1e7de26452.shtml",sourceLabel:"门票政策"},
yongan:{channel:"微信小程序",name:"北岳云游",alt:"恒山景区公众号",kind:"预约购票",route:"进入“北岳云游” → 景点购票 → 永安寺 → 选择日期与票种 → 实名购票。",tip:"恒山景区现行官方平台可预订7日内票，永安寺20元、圆觉寺20元或联票30元；截至9月17日未发现2026国庆专项新规。",source:"https://www.byhs.net.cn/culture_detial/151.html",sourceLabel:"景区票务"},
yuanjue:{channel:"微信小程序",name:"北岳云游",alt:"恒山景区公众号",kind:"预约购票",route:"进入“北岳云游” → 景点购票 → 圆觉寺 → 选择日期与票种 → 实名购票。",tip:"现行可预订7日内票，可与永安寺购买联票；截至9月17日未发现2026国庆专项新规。行程当天圆觉寺仍作为可压缩项。",source:"https://www.byhs.net.cn/culture_detial/151.html",sourceLabel:"景区票务"},
yingxian:{channel:"微信公众号 / 小程序",name:"应县木塔景区",alt:"游山西",kind:"预约购票",route:"微信搜索“应县木塔景区”进入门票预约，或在“游山西”小程序搜索应县木塔后实名购票。",tip:"2026春节曾严格执行分时、预约、错峰；截至9月17日尚未检索到国庆专项新公告。国庆仍按高客流景点处理，建议一开放可售日期就提前购买，并继续关注景区服务号。",source:"https://www.sohu.com/a/987399807_121956422",sourceLabel:"2026预约规则参考"},
jinci:{channel:"微信小程序 / 公众号",name:"太原市文保院",alt:"中国晋祠 / 晋祠天龙山景区官微",kind:"国庆实名分时预约",route:"微信搜索“太原市文保院”小程序，或进入“中国晋祠”“晋祠天龙山景区官微” → 预约购票 → 选择晋祠博物馆 → 选择10月7日与时段 → 实名购票。购票即完成预约。",tip:"2026年9月15日最新公告：国庆等重要节假日严格实行预约限流，可提前10天预约；每日、每时段均设上限，约满关闭，原则上不开放临时登记入馆。你们10月7日参观，按10天规则最早可在9月27日关注并预约。多数免费优待人群也须提前预约；国庆期间一卡通不可使用。",source:"https://finance.sina.com.cn/jjxw/2026-09-15/doc-inirxaty3745325.shtml",sourceLabel:"9/15最新预约公告"}
};
const legacyPlaceBookingPanel=placeBookingPanel;
function lightTicketPanel(id,b){return `<div class="place-ticket-panel"><div class="place-ticket-head"><span>Booking / 预约购票</span><strong>${b.kind||'线上入口'}</strong></div><div class="ticket-channel">${b.channel}</div><div class="ticket-name">${b.name}${b.alt?` <span>/ ${b.alt}</span>`:''}</div><div class="ticket-route">${b.route}</div><div class="ticket-actions"><button class="copy-booking" data-booking="${b.name}">复制入口名</button>${b.source?`<a href="${b.source}" target="_blank" rel="noopener">${b.sourceLabel||'购票说明'} ↗</a>`:''}</div>${b.tip?`<div class="ticket-tip">${b.tip}</div>`:''}</div>`}
placeBookingPanel=function(id){let legacy=legacyPlaceBookingPanel(id);if(legacy)return legacy;let b=PLACE_TICKETS[id];return b?lightTicketPanel(id,b):''};
function dayTicketSummary(day){let actionPlace={"1002":"beiqi","1003":"yungang","1004":"hanging"}[day[0]],seen=new Set(),rows=[];day[8].forEach(s=>{let id=s[2],b=PLACE_TICKETS[id];if(!id||!b||id===actionPlace||seen.has(id))return;seen.add(id);rows.push(`<div class="day-ticket-row"><div><b>${P[id]?.n||s[1]}</b><span>${b.name}</span></div><div class="day-ticket-actions"><button class="copy-booking" data-booking="${b.name}">复制入口</button>${b.source?`<a href="${b.source}" target="_blank" rel="noopener">${b.sourceLabel||'说明'} ↗</a>`:''}</div></div>`)});if(!rows.length)return'';return `<div class="day-ticket-summary"><div class="day-ticket-title"><span>Reservation / 预约购票</span><b>本日可线上处理</b></div>${rows.join('')}</div>`}
function bindTicketSummary(root=document){bindBookingLinks(root)}