const PLACE_TICKETS={
shuanglin:{channel:"微信公众号",name:"平遥古城景区官方服务平台",kind:"预约购票",route:"游客服务 → 古城购票 → 双林寺 → 选择日期与时段 → 添加实名游客信息 → 完成购票。",tip:"2026年7月起千佛殿处于半封闭保护修缮期，国庆前需再次核实具体开放范围。",source:"https://www.pygc.com/single/13",sourceLabel:"预约说明"},
zhenguo:{channel:"微信公众号",name:"平遥古城景区官方服务平台",kind:"预约购票",route:"游客服务 → 古城购票 → 镇国寺 → 选择日期与时段 → 添加实名游客信息 → 完成购票。",tip:"2026年7月起万佛殿处于半封闭保护修缮期，国庆前需再次核实具体开放范围。",source:"https://www.pygc.com/single/13",sourceLabel:"预约说明"},
pingyao:{channel:"微信公众号",name:"平遥古城景区官方服务平台",kind:"预约购票",route:"游客服务 → 古城购票 → 平遥古城通票 → 选择日期 → 添加实名游客信息 → 完成购票。",tip:"进入古城街区本身免费；城墙、日昇昌、县衙等收费景点使用古城通票。",source:"https://www.pygc.com/single/13",sourceLabel:"游览须知"},
tianlongshan:{channel:"微信公众号",name:"晋祠天龙山景区官微",alt:"太原市天龙山石窟博物馆",kind:"预约购票",route:"进入公众号 → 票务/线上购票 → 选择天龙山石窟博物馆 → 填写实名信息并支付。",tip:"景区实行线上线下一体化售票；国庆客流较高，建议提前线上处理。",source:"https://www.tylyhy.cn/wenlvzixun/1602111355401728001.html",sourceLabel:"官方说明"},
huayan:{channel:"微信小程序",name:"古都大同",alt:"大同华严寺景区公众号",kind:"预约购票",route:"古都大同 → 购票 → 大同华严寺景区 → 选择日期与票种 → 实名支付。",tip:"华严寺现有线上售票系统；国庆专项开放时间以节前公告为准。",source:"https://www.dt.gov.cn/dtszf/bumdtku/202604/636edf31b8b44e0088994000fbdcb6e4.shtml",sourceLabel:"官方渠道"},
shanhua:{channel:"微信小程序",name:"古都大同",alt:"大同善化寺公众号",kind:"预约购票",route:"古都大同 → 购票 → 善化寺 → 选择参观日期与时段 → 实名支付。",tip:"善化寺已恢复收费并支持线上购票，国庆建议提前购买。",source:"https://www.dt.gov.cn/dtszf/bumdtku/202604/636edf31b8b44e0088994000fbdcb6e4.shtml",sourceLabel:"官方渠道"},
yongan:{channel:"微信小程序",name:"北岳云游",alt:"恒山景区公众号",kind:"预约购票",route:"进入“北岳云游” → 景点购票 → 永安寺 → 选择日期与票种 → 实名购票。",tip:"恒山景区官方平台可预售7日内门票；永安寺与圆觉寺亦有联票选项。",source:"https://www.byhs.net.cn/culture_detial/151.html",sourceLabel:"景区票务"},
yuanjue:{channel:"微信小程序",name:"北岳云游",alt:"恒山景区公众号",kind:"预约购票",route:"进入“北岳云游” → 景点购票 → 圆觉寺 → 选择日期与票种 → 实名购票。",tip:"可与永安寺购买联票；行程当天圆觉寺仍作为可压缩项。",source:"https://www.byhs.net.cn/culture_detial/151.html",sourceLabel:"景区票务"},
yingxian:{channel:"微信公众号 / 小程序",name:"应县木塔景区",alt:"游山西",kind:"预约购票",route:"微信搜索“应县木塔景区”进入门票预约，或在“游山西”小程序搜索应县木塔后实名购票。",tip:"线上购票后通常可凭身份证或电子凭证核销；国庆前再次复核是否启用专项分时预约。",source:"https://www.younichuang.com/spots/show_240.html",sourceLabel:"渠道说明"},
jinci:{channel:"微信公众号",name:"中国晋祠",alt:"晋祠天龙山景区官微",kind:"预约购票",route:"智慧晋祠 → 线上购票 → 晋祠博物馆 → 选择日期/时段 → 填写实名信息并支付。",tip:"2026年五一已明确执行预约购票；国庆大客流期建议沿用提前预约思路并关注余票。",source:"https://www.sohu.com/a/1016367779_121123809",sourceLabel:"馆方公告转载"}
};
const legacyPlaceBookingPanel=placeBookingPanel;
function lightTicketPanel(id,b){return `<div class="place-ticket-panel"><div class="place-ticket-head"><span>Booking / 预约购票</span><strong>${b.kind||'线上入口'}</strong></div><div class="ticket-channel">${b.channel}</div><div class="ticket-name">${b.name}${b.alt?` <span>/ ${b.alt}</span>`:''}</div><div class="ticket-route">${b.route}</div><div class="ticket-actions"><button class="copy-booking" data-booking="${b.name}">复制入口名</button>${b.source?`<a href="${b.source}" target="_blank" rel="noopener">${b.sourceLabel||'购票说明'} ↗</a>`:''}</div>${b.tip?`<div class="ticket-tip">${b.tip}</div>`:''}</div>`}
placeBookingPanel=function(id){let legacy=legacyPlaceBookingPanel(id);if(legacy)return legacy;let b=PLACE_TICKETS[id];return b?lightTicketPanel(id,b):''};
function dayTicketSummary(day){let actionPlace={"1002":"beiqi","1003":"yungang","1004":"hanging","1007":"shanxi_museum"}[day[0]],seen=new Set(),rows=[];day[8].forEach(s=>{let id=s[2],b=PLACE_TICKETS[id];if(!id||!b||id===actionPlace||seen.has(id))return;seen.add(id);rows.push(`<div class="day-ticket-row"><div><b>${P[id]?.n||s[1]}</b><span>${b.name}</span></div><div class="day-ticket-actions"><button class="copy-booking" data-booking="${b.name}">复制入口</button>${b.source?`<a href="${b.source}" target="_blank" rel="noopener">说明 ↗</a>`:''}</div></div>`)});if(!rows.length)return'';return `<div class="day-ticket-summary"><div class="day-ticket-title"><span>Reservation / 预约购票</span><b>本日可线上处理</b></div>${rows.join('')}</div>`}
function bindTicketSummary(root=document){bindBookingLinks(root)}